### ISSUE TITLE
Merging efforts with Chromebrew.

### ISSUE THREAD

**Issue by JL2210** [ryanwoodsmall/crosware#1]
This program looks impressive! I noticed that you linked to Chromebrew. I was wondering if we could merge these efforts. After all, it would be a waste to have two Chrome OS package managers that work against one another. What do you say?

**Comment by ryanwoodsmall** [comment]
Hey there! I appreciate the offer, but the goals of the project are to be "pure bash," as statically-linked as possible, text-only (i.e, no X11/Wayland/etc. for now, maybe ever), and minimalist, while matching my own personal use case. I'm working towards moving away from the initial java/jgit idea towards something bootstrap-able with only bash, curl, a POSIX-ish userspace, and a single-binary git client that doesn't yet exist. Chromebrew is great, but my priorities are in very different places.

**Comment by JL2210** [comment]
That's fair. You should also see my "bootstrap.sh" Gist that bootstraps
Gentoo Prefix on a bare Chrome OS system.

**Comment by ryanwoodsmall** [comment]
The project is completely self-hosting at this point, sans the JVM (which is no longer a requirement if a real Git client is available to replace jgit), but I initially built on Alpine chroots on Chrome OS and/or Docker containers. Nearly every portion the project is at least automatable, but I don't currently/yet have a public CI/CD stack.
