### ISSUE TITLE
Feature Request: Ability to Choose Target Architecture

### ISSUE THREAD

**Issue by Kyliekyler** [ryanwoodsmall/crosware#3]
I'm looking forward to being able to choose architecture during installation. I can currently build for aarch64, but I need to make one for arm architecture for certain folks who have 32bit devices.

**Comment by ryanwoodsmall** [comment]
install the `cwstaticbinaries` recipe and preface your `crosware` commands with `linux32` or create a shell alias/script wrapper to run 32-bit architecture binaries on 64-bit hosts. choosing architectures is beyond the scope of this project and may not work in all cases. no multiarch support is planned and will not be provided as it severely complicates things. additionally, 32-bit support for Chrome OS, which is the primary target for the project, is essentially a non-starter and will never receive as much support as 64-bit architectures.
